version: '3.4'

services:
  my_zookeeper:
    # image: wurstmeister/zookeeper
    image: zookeeper:3.4.11
    container_name: 'my_zookeeper'
    restart: always
    ports:
      - 2181:2181
  my_kafka:
    image: wurstmeister/kafka:1.0.1
    container_name: 'my_kafka'
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - my_zookeeper
    links:
      - my_zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "${KAFKA_ADVERTISED_HOST_NAME}"
      KAFKA_ZOOKEEPER_CONNECT: 'my_zookeeper'
      LOG4J_LOGGER_KAFKA: 'DEBUG'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

