server:
  port: 8080
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.tnmk.pro02consumemultipleversions.common.kafka.serialization.protobuf.ProtobufSerializer
